---
version: "2.0"
services:
  web:
    image: ovrclk/lunie-light
    expose:
      - port: 3000
        as: 80
        to:
          - global: true
profiles:
  compute:
    web:
      resources:
        cpu:
          units: 0.1
        memory:
          size: 512Mi
        storage:
          size: 512Mi
  placement:
    ewr1-provider0:
      attributes:
        host: akash
        datacenter: equinix-metal-ewr1
        generation: mn2-ng
      signedBy:
        anyOf:
          - akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63
      pricing:
        web: 
          denom: uakt
          amount: 100
deployment:
  web:
    ewr1-provider0:
      profile: web
      count: 1
